final List<Map<String, dynamic>> tasks = [
  {
    'budget': 5,
    'category': 'Care for loved ones',
    'description': [
      'Send a heartfelt text to a loved one, letting them know how much they mean to you.',
      'Buy a coffee or snack for a friend or family member.',
      'Leave a kind note for someone to find later.',
      'Offer to run a small errand for a busy loved one.',
      'Create a simple DIY gift (like a friendship bracelet or small painting).',
      'Make a playlist of uplifting songs for someone special.',
      'Send a funny or thoughtful e-card.',
      'Offer to water a neighbor\'s plants while they\'re away.',
      'Bake a small batch of cookies and share with someone.',
      'Bring a friend or family member their favorite snack.',
      'Buy a small bunch of flowers for someone.',
      'Share a list of your favorite books or movies with a friend.',
      'Write down 10 reasons why you appreciate someone and give it to them.',
      'Call a friend or family member just to chat and check in.',
      'Give a genuine compliment to someone you love.',
      'Offer to babysit a pet for a few hours.',
      'Bring over a hot drink to a friend who’s feeling down.',
      'Leave a surprise thank-you note for someone who helped you.',
      'Surprise a loved one with their favorite candy.',
      'Send a friend an inspirational quote that reminds you of them.',
    ],
  },
  {
    'budget': 10,
    'category': 'Care for loved ones',
    'description': [
      'Treat a friend or family member to their favorite dessert.',
      'Buy a small potted plant and gift it to someone who loves nature.',
      'Get a scented candle for someone who needs relaxation.',
      'Put together a small care package with snacks and goodies.',
      'Purchase a reusable coffee cup for someone who loves coffee.',
      'Buy a set of pens or notebooks for a friend who loves to write.',
      'Gift a cute keychain to remind someone of your friendship.',
      'Bring a coworker or friend their favorite smoothie.',
      'Buy a small framed photo of a memory you share with someone.',
      'Get a travel-sized lotion or hand sanitizer as a thoughtful gesture.',
      'Treat a friend to an ice cream outing.',
      'Gift a cozy pair of socks for a loved one.',
      'Pick up a good book from a secondhand store to share.',
      'Purchase a coffee or tea sampler for a friend who loves warm drinks.',
      'Get a fun reusable tote bag for someone.',
      'Surprise a loved one with a fun pen set or art supplies.',
      'Give a friend a journal or diary as a thoughtful gift.',
      'Buy a small puzzle or game to enjoy together.',
      'Make a photo collage of good times and gift it.',
      'Take a friend out for a quick lunch or snack.',
    ],
  },
  {
    'budget': 20,
    'category': 'Care for loved ones',
    'description': [
      'Take a friend out for a meal at a casual restaurant.',
      'Buy a high-quality mug and fill it with treats.',
      'Order a personalized keychain or small accessory.',
      'Buy a relaxing bath bomb set for someone who needs a break.',
      'Gift a small succulent garden kit.',
      'Take a loved one to the movies.',
      'Give a loved one a small self-care gift box.',
      'Purchase a board game for a family game night.',
      'Get a personalized photo calendar with favorite memories.',
      'Arrange a surprise grocery delivery with essentials and treats.',
      'Buy a set of tea blends for a tea-loving friend.',
      'Gift a sketchbook and pencils to a creative person.',
      'Buy a cozy blanket for someone who loves to relax at home.',
      'Offer a loved one a home-cooked dinner, with groceries bought by you.',
      'Treat someone to a car wash or detailing session.',
      'Gift a small painting or poster of a meaningful place.',
      'Buy a one-month streaming service subscription for someone.',
      'Get a travel mug and fill it with snacks or notes.',
      'Treat a friend or family member to a manicure kit.',
      'Gift a high-quality reusable water bottle.',
    ],
  },
  {
    'budget': 30,
    'category': 'Care for loved ones',
    'description': [
      'Take a loved one out to brunch at their favorite cafe.',
      'Purchase a small indoor plant for their home or office.',
      'Buy a journal with personalized notes on every few pages.',
      'Gift a 3-month magazine subscription tailored to their interests.',
      'Purchase a set of quality skincare products.',
      'Buy a gourmet meal kit or cooking set for a fun night in.',
      'Surprise them with a set of art supplies or adult coloring books.',
      'Buy a high-quality puzzle for a relaxing activity.',
      'Gift a digital photo frame loaded with cherished pictures.',
      'Give them a cozy scarf or beanie for cold days.',
      'Treat a friend to a virtual class or workshop they’re interested in.',
      'Buy a calming essential oil set for relaxation.',
      'Get a good-quality recipe book for a friend who loves cooking.',
      'Buy a set of high-quality stationery or planners.',
      'Gift a small Bluetooth speaker for listening to music anywhere.',
      'Offer a spa day at home, with face masks, candles, and bath salts.',
      'Purchase a framed print of their favorite quote or artwork.',
      'Treat someone to a local tour or experience in their city.',
      'Gift a personalized T-shirt or tote bag.',
      'Get a set of cozy pillows or cushions for their home.',
    ],
  },
];
